[package]
name = "rx_rust_mp"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.25", features = ["thread-pool"]}
num-traits = { version = "0.2.15", optional = true}

[features]
default = ["math"]
math = ["dep:num-traits"]